title: Really Simple # Title of site.

# archives_link_caption: More Posts

timezone: America/Los_Angeles

sass:
   sass_dir: _sass
   style: :compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
