title: Really Simple # Title of site.
timezone: America/Los_Angeles

sass:
   sass_dir: _sass
   style: :compressed

repository: jusx/jusx.github.io

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
