title: Really Simple # Title of site.
post_limit: 3  # Number of posts to display on the home page.

timezone: America/Los_Angeles

sass:
   sass_dir: _sass
   style: :compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
